import type { Metadata } from "next";
import { Pathway_Extreme } from "next/font/google";
import "./globals.css";

const pathway_Extreme = Pathway_Extreme({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pathway_Extreme.className}>{children}</body>
    </html>
  );
}
